version: 2.1
jobs:
  build:
    docker:
      - image: henrydashwood/hakyll
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            # find a cache for the same stack.yaml
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            # when missing reuse from the same branch
            - stack-{{ .Branch }}-
            # when missing reuse the latest cache
            - stack-
      - run:
          name: Resolve/Update Dependencies
          command: stack setup && stack build --dependencies-only
      - save_cache:
          name: Cache Dependencies
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Build Site App
          command: stack build --pedantic
      - run:
          name: Generate Static Site
          command: stack exec site build
