version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
jobs:
  build:
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    docker:
      - image: henrydashwood/hakyll
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            # find a cache for the same stack.yaml
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            # when missing reuse from the same branch
            - stack-{{ .Branch }}-
            # when missing reuse the latest cache
            - stack-
      - run:
          name: Resolve/Update Dependencies
          command: stack setup && stack build --dependencies-only
      - save_cache:
          name: Cache Dependencies
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Build Site App
          command: stack build
      - run:
          name: Generate Static Site
          command: stack exec site rebuild
      - store_artifacts:
          path: _site
          destination: built_site
workflows:
  deploy_application:
    jobs:
      - aws-code-deploy/deploy:
          application-name: HenryDashwoodWebsite
          bundle-bucket: henry-dashwood-lightsail-bucket
          bundle-key: myS3BucketKey
          service-role-arn: arn:aws:iam::179840394599:role/CodeDeployServiceRole
          get-deployment-group-arguments:
            --deployment-group-name HenryDashwoodWebsiteDeploymentGroup
            --file-exists-behavior OVERWRITE
