version: 2.1

executors:
  default:
    docker:
      - image: henrydashwood/hakyll

orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
jobs:
  build:
    executor: default
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            # find a cache for the same stack.yaml
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            # when missing reuse from the same branch
            - stack-{{ .Branch }}-
            # when missing reuse the latest cache
            - stack-
      - run:
          name: Resolve/Update Dependencies
          command: stack setup && stack build --dependencies-only
      - save_cache:
          name: Cache Dependencies
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Build Site App
          command: stack build
      - run:
          name: Generate Static Site
          command: stack exec site rebuild
      - run:
          name: print working directory
          command: pwd
      - run:
          name: Copy appspec.yml into /_site
          command: cp appspec.yml _site/
      - run:
          name: Copy scripts folder into /_site
          command: cp -r scripts _site/
      - persist_to_workspace:
          root: .
          paths:
            - _site

workflows:
  deploy_application:
    jobs:
      - build
      - aws-code-deploy/deploy:
          requires:
            - build
          pre-steps:
            - attach_workspace:
                at: _site
          application-name: HenryDashwoodWebsite
          bundle-bucket: henry-dashwood-lightsail-bucket
          bundle-key: HenryDashwoodWebsite
          bundle-source: _site
          deployment-group: HenryDashwoodWebsiteDeploymentGroup
          service-role-arn: arn:aws:iam::179840394599:role/CodeDeployServiceRole
